# VRehab Configuration File
# Configuración del Sistema VRehab

# Robot Settings
robot:
  default_port: "COM5"  # Default COM port for Dobot Magic
  baudrate: 115200
  timeout: 5
  safe_height: 80  # Safe height in mm
  home_position:
    x: 0
    y: 0
    z: 60
    r: 0

# Movement Settings
movement:
  max_distance: 15  # Maximum movement distance in mm
  max_height_change: 10  # Maximum height change in mm
  movement_speed: 50  # Movement speed (1-100)
  pause_between_movements: 0.5  # Pause in seconds

# EEG Settings
eeg:
  stream_name: "EEG"  # LSL stream name to look for
  channels: 8  # Number of EEG channels
  sampling_rate: 250  # Expected sampling rate
  buffer_size: 1000  # Buffer size for data processing

# Machine Learning Settings
ml:
  model_type: "LogisticRegression"
  test_size: 0.2
  random_state: 42
  max_iter: 1000
  threshold_range:
    min: 100
    max: 2000
    default: 500

# GUI Settings
gui:
  theme: "dark"
  window_size:
    width: 1200
    height: 800
  update_interval: 1000  # UI update interval in ms
  log_max_lines: 1000

# Safety Settings
safety:
  emergency_stop: true
  collision_detection: true
  max_workspace:
    x_min: -200
    x_max: 200
    y_min: -200
    y_max: 200
    z_min: 0
    z_max: 300

# Logging Settings
logging:
  level: "INFO"
  file: "vrehab.log"
  max_size: "10MB"
  backup_count: 5
